version: '3.8'

services:
  # Aplicación Next.js conectada a AWS RDS
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foro-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      - ./uploads:/app/uploads
    networks:
      - foro-network

  # Adminer para gestión de base de datos AWS RDS (opcional)
  adminer:
    image: adminer:latest
    container_name: foro-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database-1.cwni8qkeq51c.us-east-1.rds.amazonaws.com
    networks:
      - foro-network

networks:
  foro-network:
    driver: bridge
